### PR TITLE
Fix ModuleNotFoundErrors in tutorial examples

### PR DESCRIPTION
**Pull request by dcslagel**
#### Description:

This addresses the issue #36 `ModuleNotFoundError: tutorial/parse.py`  It also fixes the ModuleNotFoundError in tutorial/example.py.  

- Add get_data_path() wrapper function using so that data files will be
  retrieved from the package path whether an installed or installed in
  development mode(`pip install -e` .)
- remove unused lasio import from parse.py
- Remove `__pycache__` and *.pyc files from git branch. These aren't
  usually tracked in version control (git).

#### Test results:

These changes were tested by moving the tutorial files out of the AlasKA git repo,  and running them from the new location while installing AlasKA in different scenarios:
1.  cd alaska repository and installing in developer mode: `pip install -e .`
2. build a wheel package file and install that.

In both cases the tutorial files run without the ModuleNotFound error.  

The tutorials are also updated in the repository and run from the repository location with the same to different package install scenarios as above.

The regular test suite passes with current stats
```
Name                           Stmts   Miss  Cover
--------------------------------------------------
alaska/__init__.py                 6      0   100%
alaska/_version.py               279    142    49%
alaska/get_data_path.py            7      2    71%
alaska/keyword_tree.py           297      4    99%
alaska/model.py                  303    115    62%
alaska/params.py                  56      0   100%
alaska/predict_from_model.py      86     23    73%
alaska/utils.py                  324    103    68%
--------------------------------------------------
TOTAL                           1358    389    71%
```

#### Subsequent findings:

1. tutorials/parse.py will fail with a non-ModuleNotFoundError error:
```python
IndexError: index 0 is out of bounds for axis 0 with size 0
 ```

2. tutorials/example.py will fail with a non-ModuleNotFoundError error:
```python
KeyError: "density porosity not in ['DPHI', 'QN']"
```

**Reminders**

- [x] Run `black .` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] If adding new functionality, add an example to the docstring, gallery, and/or tutorials.

Let me know if this change could be accepted (or rejected) or
needs some additional changes before being approved and merged.

Thank you,
DC

### CODE REVIEW

**Comment by jessepisel** [comment]
@dcslagel Thanks for opening the PR. I am going to hold off on merging it in for right now. I am in the process of migrating CI to GitHub actions.

From the TravisCI run it looks like your changes are good for Python 3.7 and 3.8 but failed on 3.6 with the `import error on import importlib.resources as pkg_resources`  even with the import try/except. It will be nice to have this function to access the test data no matter the install method. Can you take a look at this and see if you can get it running on 3.6 if you have the time?

I spoke with @dingdonged about dropping support for 3.6 but haven't decided yet. Any thoughts would be appreciated. That could take care of this issue. 

For the additional errors @dingdonged can you take a look at them and see what might be going on with the tutorials. Just fork this branch and see if you can replicate and trace down the error.

**Comment by dcslagel** [comment]
@jessepisel @dingdonged ,

I'll work on solving this import issue with 3.6.  It might take me a couple of days, but I'll have an update/fix.

My vote is that it would be good to keep support for 3.6 for now.  

Thanks
DC

**Comment by dcslagel** [comment]
@jessepisel @dingdonged ,

commit c41d104 adds importlib_resources to requirements.txt, so that it is available if an ImportError occurs when attempting to import `impor lib.resources`.  This should take work for python 3.6.x versions and earlier.

Once Python 3.6.x is no longer supported this change could be removed.

Thanks,
DC

**Comment by dcslagel** [comment]
I've added a maintenance note in get_data_path.py, commit 6cffa5e. This should help with maintenance when python 3.6 is no-longer supported.

**Review by jessepisel — APPROVED** [review]
@dcslagel I have reviewed your changes and they are all working with Python 3.6-3.8, we discussed supporting 3.6 until its end of support in late 2021. Having this in the repo will help get the test and example datasets no matter where they end up on the local system. Thanks for doing this!

**Pull request merged**
