### PR TITLE
Organization and structuring

### PR DESCRIPTION
**Pull request by jessepisel**
. @dingdonged can you verify that it is ok to remove these files from the top level directory back into the `alaska` directory? I also added a changelog and  contributing guidelines.

### CODE REVIEW

**Comment by jessepisel** [comment]
I finished reorganizing and restructuring the directories. I also added seaborn to `requirements.txt` which I think we will need going forward. I will close out #9 because of this. 

After reorganizing and doing a local install of the repository on my linux machine I was able to run `from alaska import Alias` which takes care of #12 . We will need to build a new source and wheel distribution for v 0.0.3

**Comment by dcslagel** [comment]
@jessepisel , 


In my environment (updated to15049e2 and with seaboar installed), `from alaska import Alias`  has the following error/Traceback

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/devel/MyWrk/geo-wrk/alaska/AlasKA/alaska/__init__.py", line 1, in <module>
    from .keyword_tree import Alias, search, make_tree, search_child
  File "/usr/local/devel/MyWrk/geo-wrk/alaska/AlasKA/alaska/keyword_tree.py", line 7, in <module>
    from predict_from_model import make_prediction
ModuleNotFoundError: No module named 'predict_from_model'
```

Is there another module that my environment might be missing?

Here is the  current virtualenv pip list:
```
 pip list
Package                       Version
----------------------------- ---------
backports.functools-lru-cache 1.6.1
certifi                       2020.6.20
cycler                        0.10.0
future                        0.18.2
kiwisolver                    1.2.0
lasio                         0.28
matplotlib                    3.3.2
numpy                         1.19.2
pandas                        1.1.2
Pillow                        7.2.0
pip                           20.2.3
pyparsing                     2.4.7
python-dateutil               2.8.1
pytz                          2020.1
scipy                         1.5.2
seaborn                       0.11.0
setuptools                    50.3.0
six                           1.15.0
torch                         1.6.0
```

DC

**Comment by jessepisel** [comment]
@dcslagel Thanks for the heads up. I was able to reproduce the error. It looks like we have a lot of directory issues in this release. I have fixed all of the directory issues that I have found so far. We are having some compatibility issues with `PyTorch` so I have a fix that I will open a PR for which sets the pointer generator model to false for the time being. 

The aliaser will take care of 80% of cases with the dictionary search and the keyword tree. Only the unusual cases will be unaliased. 

A quick rundown once you have the latest version (0.0.5) you can test to see that it is working with:
```python
from alaska import Alias
path = "alaska/data/testcase1.las"
a = Alias(model=False)
parsed, not_found = a.parse(path)`
```
If you want to test it locally without waiting for the PyPi release, you can clone this repo, navigate to the directory and run `python setup.py install` and it will install the latest version on your machine (which should work).

@dingdonged I am going to open a new PR and merge it. Will you review it and push the new source and wheel to pypi when you get a chance?

**Comment by dcslagel** [comment]
@jessepisel,  Good!  I did the clone followed by `python setup.py install`, then running the code you posted and it runs cleanly.  

The `python setup.py install` command installs AlasKA as version `0.0.1`.  It looks like this is coming from `setup.py:VERSION = '0.0.1'`.   Should it be updated to `0.0.5` now?

**Comment by jessepisel** [comment]
That's a good point. I am glad you were able to get it up and running. I think we will be moving to automatic versioning to deal with this. Thanks for bringing this up, I was focused on getting it functional and didn't even to think of updating the version number.

**Pull request merged**
